# Generated by Django 5.1.7 on 2026-09-17 10:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academic_allocation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='academic_subject',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='faculty_teacher',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='feedback_response',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='feedback_submissionlog',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('grant_token', models.CharField(db_index=True, help_text='Cryptographically secure unique token identifying this grant', max_length=64, unique=True)),
                ('session', models.CharField(help_text='Academic session, e.g. Jun-Dec 2026', max_length=50)),
                ('branch', models.CharField(help_text='Target branch, e.g. CSE(AIML)', max_length=50)),
                ('year', models.PositiveSmallIntegerField(help_text='Target year (1-4)', validators=[django.core.validators.MinValueValidator(1)])),
                ('semester', models.PositiveSmallIntegerField(help_text='Target semester (1-8)', validators=[django.core.validators.MinValueValidator(1)])),
                ('section', models.PositiveSmallIntegerField(help_text='Target section (1-10)', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('max_responses', models.PositiveIntegerField(default=100, help_text='Maximum allowed feedback submissions for this grant')),
                ('response_count', models.PositiveIntegerField(default=0, help_text='Number of responses submitted under this grant')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'access_grants',
                'ordering': ['-created_at'],
            },
        ),
    ]
